Vagrant.configure("2") do |config|

  config.vm.define "vptdemos5" do |vptdemos5|
    vptdemos5.vm.box = "gep13/PackerDemo"
    vptdemos5.windows.halt_timeout = 20
    vptdemos5.winrm.username = "vagrant"
    vptdemos5.winrm.password = "vagrant"
    vptdemos5.vm.guest = :windows
    vptdemos5.vm.communicator = "winrm"

    vptdemos5.vm.hostname = "vptdemos5"
    vptdemos5.windows.set_work_network = true

    vptdemos5.vm.network :forwarded_port, guest: 5985, host: 14985, id: "winrm", auto_correct: true
    vptdemos5.vm.network :forwarded_port, guest: 3389, host: 14389, id: "rdp", auto_correct: true
    vptdemos5.vm.network :forwarded_port, guest: 22, host: 14222, id: "ssh", auto_correct: true

    vptdemos5.vm.provider :virtualbox do |v, override|
      override.vm.network :private_network, ip: "10.10.117.14"
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.gui = true
      v.customize ["modifyvm", :id, "--vram", 32]
      v.customize ["modifyvm", :id, "--memory", "4096"]
      v.customize ["modifyvm", :id, "--audio", "none"]
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      v.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"]
      v.customize ["modifyvm", :id, "--usb", "off"]
      # linked clones for speed and size
      v.linked_clone = true if Vagrant::VERSION >= '1.8.0'
    end

  end
end
