choco upgrade dotnet4.7.2 -y
choco upgrade vscode -y
choco upgrade vscode-csharp -y
choco upgrade vscode-csharpextensions -y
choco upgrade vscode-cake -y
choco upgrade cakerecipe-vscode -y
choco upgrade chocolatey-vscode -y
choco upgrade ci-cd-assets-vscode -y
choco upgrade vscode-codespellchecker -y
choco upgrade vscode-editorconfig -y
choco upgrade vscode-markdownlint -y
choco upgrade vscode-gitignore -y
choco upgrade vscode-gitattributes -y
choco upgrade vscode-powershell -y
choco upgrade vscode-icons -y
choco upgrade vscode-autohotkey -y
choco upgrade googlechrome -y
